service: r3wy-commerce

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: eu-central-1
  timeout: 5
  memorySize: 256

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

package:
  excludeDevDependencies: true
  patterns:
    - "!tsconfig.json"
    - "!tsconfig.tsbuildinfo"
    - "!.prettierrc.cjs"
    - "!.eslintrc"
    - "!.npmrc"
    - "src/**"

functions:
  productsGetOne:
    handler: src/model.products/lambda.get-one/route.getOne
    events:
      - httpApi:
          path: /products/{id}
          method: get
  productsFindMany:
    handler: src/model.products/lambda.find-many/route.findMany
    events:
      - httpApi:
          path: /products
          method: get
