service: r3wy-commerce
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  timeout: 5
  memorySize: 256

plugins:
  - serverless-prune-plugin

custom:
  products:
    tableName: ${self:service}_${self:provider.stage}_products
  prune:
    automatic: true
    number: 3

package:
  excludeDevDependencies: true
  patterns:
    - "!tsconfig.json"
    - "!tsconfig.tsbuildinfo"
    - "!.prettierrc.cjs"
    - "!.eslintrc"
    - "!.npmrc"
    - "src/**"

functions:
  productsGetOne:
    handler: src/products/lambda.get-one/route.handler
    events:
      - httpApi:
          path: /products/{id}
          method: get
  productsFindMany:
    handler: src/products/lambda.find-many/route.handler
    events:
      - httpApi:
          path: /products
          method: get
  productsCreateOne:
    handler: src/products/lambda.create-one/route.handler
    environment:
      PRODUCTS_TABLE_NAME: ${self:custom.products.tableName}
    events:
      - httpApi:
          path: /products
          method: post

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.products.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
