service: r3wy-a2

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: eu-central-1
  timeout: 5
  memorySize: 256

plugins:
  - serverless-prune-plugin

package:
  excludeDevDependencies: true
  patterns:
    - "!tsconfig.json"
    - "!tsconfig.tsbuildinfo"
    - "!.prettierrc.cjs"
    - "!.eslintrc"
    - "!.npmrc"
    - "src/**"

custom:
  prune:
    automatic: true
    number: 3

functions:
  hello:
    handler: src/handler.helloWorld
    events:
      - httpApi:
          path: /users/create
          method: get
